title: August Nagro
email: augustnagro@gmail.com
baseurl: ""
url: "https://augustnagro.com"
twitter_username: augustnagro
github_username:  augustnagro
excerpt_separator: <!--more-->
permalink: none

# Build settings
markdown: kramdown
