(function(){
'use strict';var g,aa=Object.freeze({esVersion:6,assumingES6:!0,productionMode:!0,linkerVersion:"1.7.0",fileLevelThis:this}),l=Math.imul,ba=Math.clz32,m;function ca(a){for(var b in a)return b}function n(a){this.db=a}n.prototype.toString=function(){return String.fromCharCode(this.db)};
function da(a){switch(typeof a){case "string":return"java.lang.String";case "number":return"number"===typeof a&&(a|0)===a&&1/a!==1/-0?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":"java.lang.Float";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.Ld():a instanceof v?"java.lang.Long":a instanceof n?"java.lang.Character":a&&a.$classData?a.$classData.name:null.Md()}}
function ea(a,b){switch(typeof a){case "string":return a===b;case "number":return Object.is(a,b);case "boolean":return a===b;case "undefined":return a===b;default:return a&&a.$classData||null===a?a.s(b):a instanceof n?b instanceof n?w(a)===w(b):!1:x.prototype.s.call(a,b)}}
function fa(a){switch(typeof a){case "string":return y(a);case "number":return ha(a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.w():a instanceof n?w(a):x.prototype.w.call(a)}}function ia(a){return void 0===a?"undefined":a.toString()}var ja=0,ka=new WeakMap;
function la(a){switch(typeof a){case "string":return y(a);case "number":return ha(a);case "bigint":var b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:y(a);default:if(null===a)return 0;b=ka.get(a);void 0===b&&(ja=b=ja+1|0,ka.set(a,b));return b}}function w(a){return null===a?0:a.db}function x(){}x.prototype.constructor=x;function A(){}
A.prototype=x.prototype;x.prototype.w=function(){return la(this)};x.prototype.s=function(a){return this===a};x.prototype.i=function(){var a=this.w();return da(this)+"@"+(+(a>>>0)).toString(16)};x.prototype.toString=function(){return this.i()};function ma(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=null}else this.a=a}ma.prototype=new A;ma.prototype.constructor=ma;function na(){}na.prototype=ma.prototype;
function B(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=!1}else this.a=a}B.prototype=new A;B.prototype.constructor=B;function C(a){this.a="number"===typeof a?new Uint16Array(a):a}C.prototype=new A;C.prototype.constructor=C;function E(a){this.a="number"===typeof a?new Int8Array(a):a}E.prototype=new A;E.prototype.constructor=E;function F(a){this.a="number"===typeof a?new Int16Array(a):a}F.prototype=new A;F.prototype.constructor=F;
function G(a){this.a="number"===typeof a?new Int32Array(a):a}G.prototype=new A;G.prototype.constructor=G;function H(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=m}else this.a=a}H.prototype=new A;H.prototype.constructor=H;function I(a){this.a="number"===typeof a?new Float32Array(a):a}I.prototype=new A;I.prototype.constructor=I;function J(a){this.a="number"===typeof a?new Float64Array(a):a}J.prototype=new A;J.prototype.constructor=J;
function oa(){this.r=void 0;this.ca=this.q=null;this.da=0;this.Jb=null;this.H="";this.T=this.ba=void 0;this.name="";this.isJSClass=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function K(a,b,c,e){var d=new oa;d.q={};d.Jb=a;d.H=b;d.T=k=>k===d;d.name=c;d.isPrimitive=!0;d.isInstance=()=>!1;void 0!==e&&(d.ba=pa(d,e));return d}
function L(a,b,c,e){var d=new oa,k=ca(a);d.q=c;d.H="L"+b+";";d.T=h=>!!h.q[k];d.name=b;d.isInterface=!1;d.isInstance=e||(h=>!!(h&&h.$classData&&h.$classData.q[k]));return d}function pa(a,b,c){var e=new oa;b.prototype.$classData=e;var d="["+a.H;e.r=b;e.q={b:1,Oa:1,c:1};e.ca=a;e.da=1;e.H=d;e.name=d;e.isArrayClass=!0;e.T=c||(k=>e===k);e.isInstance=k=>k instanceof b;return e}
function qa(a){function b(h){if("number"===typeof h){this.a=Array(h);for(var f=0;f<h;f++)this.a[f]=null}else this.a=h}var c=new oa;b.prototype=new na;b.prototype.constructor=b;var e=a.ca||a,d=a.da+1;b.prototype.$classData=c;a="["+a.H;c.r=b;c.q={b:1,Oa:1,c:1};c.ca=e;c.da=d;c.H=a;c.name=a;c.isArrayClass=!0;var k=h=>{var f=h.da;return f===d?e.T(h.ca):f>d&&e===M};c.T=k;c.isInstance=h=>{h=h&&h.$classData;return!!h&&(h===c||k(h))};return c}function N(a){a.ba||(a.ba=qa(a));return a.ba}var M=new oa;M.q={b:1};
M.H="Ljava.lang.Object;";M.T=a=>!a.isPrimitive;M.name="java.lang.Object";M.isInstance=a=>null!==a;M.ba=pa(M,ma,a=>{var b=a.da;return 1===b?!a.ca.isPrimitive:1<b});x.prototype.$classData=M;K(void 0,"V","void",void 0);K(!1,"Z","boolean",B);K(0,"C","char",C);K(0,"B","byte",E);K(0,"S","short",F);K(0,"I","int",G);var ra=K(null,"J","long",H);K(0,"F","float",I);K(0,"D","double",J);
function sa(){this.u=this.d=null;ta=this;for(var a=new (N(N(ua)).r)(9),b=0;9>b;){for(var c=b,e=new (N(ua).r)(9),d=0;9>d;){var k=d,h=document.createElement("input");h.type="text";h.size="1";h.style="font-weight: bold";e.a[k]=h;d=1+d|0}a.a[c]=e;b=1+b|0}this.d=a;a=new (N(N(va)).r)(9);for(b=0;9>b;){c=b;e=new (N(va).r)(9);for(d=0;9>d;)e.a[d]=wa(),d=1+d|0;a.a[c]=e;b=1+b|0}this.u=a}sa.prototype=new A;sa.prototype.constructor=sa;
function xa(){var a=O(),b=ya,c=document.createElement("div"),e=document.createElement("div");e.id="board";var d=O().d,k=((p,q)=>u=>{var z=((ye,le)=>me=>le.appendChild(me))(p,q),D=u.a.length,t=0;if(null!==u)for(;t<D;)z(u.a[t]),t=1+t|0;else if(u instanceof G)for(;t<D;)z(u.a[t]),t=1+t|0;else if(u instanceof J)for(;t<D;)z(u.a[t]),t=1+t|0;else if(u instanceof H)for(;t<D;){var Uc=u.a[t];z(new v(Uc.m,Uc.l));t=1+t|0}else if(u instanceof I)for(;t<D;)z(u.a[t]),t=1+t|0;else if(u instanceof C)for(;t<D;)z(new n(u.a[t])),
t=1+t|0;else if(u instanceof E)for(;t<D;)z(u.a[t]),t=1+t|0;else if(u instanceof F)for(;t<D;)z(u.a[t]),t=1+t|0;else if(u instanceof B)for(;t<D;)z(u.a[t]),t=1+t|0;else throw new P(u);})(a,e),h=d.a.length,f=0;if(null!==d)for(;f<h;)k(d.a[f]),f=1+f|0;else if(d instanceof G)for(;f<h;)k(d.a[f]),f=1+f|0;else if(d instanceof J)for(;f<h;)k(d.a[f]),f=1+f|0;else if(d instanceof H)for(;f<h;){var r=d.a[f];k(new v(r.m,r.l));f=1+f|0}else if(d instanceof I)for(;f<h;)k(d.a[f]),f=1+f|0;else if(d instanceof C)for(;f<
h;)k(new n(d.a[f])),f=1+f|0;else if(d instanceof E)for(;f<h;)k(d.a[f]),f=1+f|0;else if(d instanceof F)for(;f<h;)k(d.a[f]),f=1+f|0;else if(d instanceof B)for(;f<h;)k(d.a[f]),f=1+f|0;else throw new P(d);c.appendChild(e);e=document.createElement("button");e.appendChild(document.createTextNode("Click to solve"));d=new Q((()=>()=>{za()})(a));e.onclick=Aa(Ba(),d);c.appendChild(e);e=document.createElement("button");e.appendChild(document.createTextNode("Clear"));a=new Q((()=>()=>{Ca()})(a));e.onclick=Aa(Ba(),
a);c.appendChild(e);b.appendChild(c)}function Da(){O();for(var a=0;9>a;){for(var b=0;9>b;){var c=O().d.a[a].a[b],e=""+Ea(O(),O().u.a[a].a[b]);c.value=e;b=1+b|0}a=1+a|0}}
function za(){for(var a=O(),b=0;9>b;){for(var c=0;9>c;){var e=O().d.a[b].a[c],d=e.value;e.setAttribute("readonly","true");if(null===d||""===d)e.style="",O().u.a[b].a[c]=wa();else{e=O().u.a[b];var k=c;d=Fa(Ga(),d);e.a[k]=new R(d)}c=1+c|0}b=1+b|0}c=b=b=0;for(c=-1;8===c?(b=1+b|0,c=0):c=1+c|0,9!==b&&O().u.a[b].a[c]instanceof R;);for(;9!==b;)if(d=O().u.a[b].a[c],d=Ea(O(),d),9>d){if(d=1+d|0,O().u.a[b].a[c]=new Ha(d),Ia(O(),b,c))for(;8===c?(b=1+b|0,c=0):c=1+c|0,9!==b&&O().u.a[b].a[c]instanceof R;);}else for(O().u.a[b].a[c]=
wa();0===c?(b=-1+b|0,c=8):c=-1+c|0,O().u.a[b].a[c]instanceof R;);Ja();Da();b=O().d;a=(h=>f=>{var r=(()=>z=>z.removeAttribute("readonly"))(h),p=f.a.length,q=0;if(null!==f)for(;q<p;)r(f.a[q]),q=1+q|0;else if(f instanceof G)for(;q<p;)r(f.a[q]),q=1+q|0;else if(f instanceof J)for(;q<p;)r(f.a[q]),q=1+q|0;else if(f instanceof H)for(;q<p;){var u=f.a[q];r(new v(u.m,u.l));q=1+q|0}else if(f instanceof I)for(;q<p;)r(f.a[q]),q=1+q|0;else if(f instanceof C)for(;q<p;)r(new n(f.a[q])),q=1+q|0;else if(f instanceof
E)for(;q<p;)r(f.a[q]),q=1+q|0;else if(f instanceof F)for(;q<p;)r(f.a[q]),q=1+q|0;else if(f instanceof B)for(;q<p;)r(f.a[q]),q=1+q|0;else throw new P(f);})(a);c=b.a.length;d=0;if(null!==b)for(;d<c;)a(b.a[d]),d=1+d|0;else if(b instanceof G)for(;d<c;)a(b.a[d]),d=1+d|0;else if(b instanceof J)for(;d<c;)a(b.a[d]),d=1+d|0;else if(b instanceof H)for(;d<c;)e=b.a[d],a(new v(e.m,e.l)),d=1+d|0;else if(b instanceof I)for(;d<c;)a(b.a[d]),d=1+d|0;else if(b instanceof C)for(;d<c;)a(new n(b.a[d])),d=1+d|0;else if(b instanceof
E)for(;d<c;)a(b.a[d]),d=1+d|0;else if(b instanceof F)for(;d<c;)a(b.a[d]),d=1+d|0;else if(b instanceof B)for(;d<c;)a(b.a[d]),d=1+d|0;else throw new P(b);}function Ea(a,b){a=wa();if(null===a?null===b:a.s(b))return 0;if(b instanceof R)return b.$;if(b instanceof Ha)return b.aa;throw new P(b);}
function Ia(a,b,c){a=O().u;for(var e=Ea(O(),a.a[b].a[c]),d=0;9>d;){if(Ea(O(),a.a[d].a[c])===e&&d!==b)return!1;d=1+d|0}for(d=0;9>d;){if(Ea(O(),a.a[b].a[d])===e&&d!==c)return!1;d=1+d|0}d=l(3,b/3|0);for(var k=l(3,c/3|0),h=0;3>h;){for(var f=0;3>f;){var r=d+h|0,p=k+f|0;if(Ea(O(),a.a[r].a[p])===e&&(r!==b||p!==c))return!1;f=1+f|0}h=1+h|0}return!0}
function Ca(){var a=O(),b=O().d;a=(k=>h=>{var f=(()=>u=>{u.value=""})(k),r=h.a.length,p=0;if(null!==h)for(;p<r;)f(h.a[p]),p=1+p|0;else if(h instanceof G)for(;p<r;)f(h.a[p]),p=1+p|0;else if(h instanceof J)for(;p<r;)f(h.a[p]),p=1+p|0;else if(h instanceof H)for(;p<r;){var q=h.a[p];f(new v(q.m,q.l));p=1+p|0}else if(h instanceof I)for(;p<r;)f(h.a[p]),p=1+p|0;else if(h instanceof C)for(;p<r;)f(new n(h.a[p])),p=1+p|0;else if(h instanceof E)for(;p<r;)f(h.a[p]),p=1+p|0;else if(h instanceof F)for(;p<r;)f(h.a[p]),
p=1+p|0;else if(h instanceof B)for(;p<r;)f(h.a[p]),p=1+p|0;else throw new P(h);})(a);var c=b.a.length,e=0;if(null!==b)for(;e<c;)a(b.a[e]),e=1+e|0;else if(b instanceof G)for(;e<c;)a(b.a[e]),e=1+e|0;else if(b instanceof J)for(;e<c;)a(b.a[e]),e=1+e|0;else if(b instanceof H)for(;e<c;){var d=b.a[e];a(new v(d.m,d.l));e=1+e|0}else if(b instanceof I)for(;e<c;)a(b.a[e]),e=1+e|0;else if(b instanceof C)for(;e<c;)a(new n(b.a[e])),e=1+e|0;else if(b instanceof E)for(;e<c;)a(b.a[e]),e=1+e|0;else if(b instanceof
F)for(;e<c;)a(b.a[e]),e=1+e|0;else if(b instanceof B)for(;e<c;)a(b.a[e]),e=1+e|0;else throw new P(b);}sa.prototype.$classData=L({Kb:0},"SodokuSolver$package$",{Kb:1,b:1});var ta;function O(){ta||(ta=new sa);return ta}function Ka(){this.jb=this.xa=this.ea=null;La=this;this.ea=new ArrayBuffer(8);this.xa=new Int32Array(this.ea,0,2);new Float32Array(this.ea,0,2);this.jb=new Float64Array(this.ea,0,1);this.xa[0]=16909060;new Int8Array(this.ea,0,8)}Ka.prototype=new A;Ka.prototype.constructor=Ka;
function Ma(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;a.jb[0]=b;return(a.xa[0]|0)^(a.xa[1]|0)}Ka.prototype.$classData=L({ac:0},"java.lang.FloatingPointBits$",{ac:1,b:1});var La;function Na(){La||(La=new Ka);return La}function Oa(){this.kb=null;Pa=this;this.kb=new Qa(!1);new Qa(!0)}Oa.prototype=new A;Oa.prototype.constructor=Oa;Oa.prototype.$classData=L({jc:0},"java.lang.System$Streams$",{jc:1,b:1});var Pa;function Ra(){Pa||(Pa=new Oa);return Pa}
function Sa(){this.lb=this.Pa=null;Ta=this;var a={"java.version":"1.8","java.vm.specification.version":"1.8","java.vm.specification.vendor":"Oracle Corporation","java.vm.specification.name":"Java Virtual Machine Specification","java.vm.name":"Scala.js"};a["java.vm.version"]=aa.linkerVersion;a["java.specification.version"]="1.8";a["java.specification.vendor"]="Oracle Corporation";a["java.specification.name"]="Java Platform API Specification";a["file.separator"]="/";a["path.separator"]=":";a["line.separator"]=
"\n";this.Pa=a;this.lb=null}Sa.prototype=new A;Sa.prototype.constructor=Sa;function Ua(a,b,c){null!==a.Pa?(Va||(Va=new Wa),a=a.Pa,Xa||(Xa=new Ya),b=Xa.nb.call(a,b)?a[b]:c):b=Ua(a.lb,b,c);return b}Sa.prototype.$classData=L({kc:0},"java.lang.System$SystemProperties$",{kc:1,b:1});var Ta;function Wa(){}Wa.prototype=new A;Wa.prototype.constructor=Wa;Wa.prototype.$classData=L({pc:0},"java.lang.Utils$",{pc:1,b:1});var Va;function Ya(){this.nb=null;Xa=this;this.nb=Object.prototype.hasOwnProperty}
Ya.prototype=new A;Ya.prototype.constructor=Ya;Ya.prototype.$classData=L({qc:0},"java.lang.Utils$Cache$",{qc:1,b:1});var Xa;function Za(){}Za.prototype=new A;Za.prototype.constructor=Za;Za.prototype.$classData=L({rc:0},"java.util.Arrays$",{rc:1,b:1});var $a;function ab(){}ab.prototype=new A;ab.prototype.constructor=ab;ab.prototype.$classData=L({Sb:0},"org.getshaka.shaka.Helpers$package$",{Sb:1,b:1});var bb;
function cb(a,b,c){if(a.e())a=""+b+")";else{var e=a.ra,d=new db;d.A=eb(new S);a=e.call(a,d,b,c,")").A.f}return a}function fb(a,b,c,e,d){var k=b.A;0!==(c.length|0)&&(k.f=""+k.f+c);a=a.o();if(a.j())for(c=a.k(),k.f=""+k.f+c;a.j();)k.f=""+k.f+e,c=a.k(),k.f=""+k.f+c;0!==(d.length|0)&&(k.f=""+k.f+d);return b}function gb(){this.Hb=null;hb=this;this.Hb=new ma(0);new (N(N(M)).r)(0);new (N(N(N(M))).r)(0);new (N(N(N(N(M)))).r)(0);new (N(N(N(N(N(M))))).r)(0);new (N(N(N(N(N(N(M)))))).r)(0)}gb.prototype=new A;
gb.prototype.constructor=gb;gb.prototype.$classData=L({rd:0},"scala.collection.immutable.VectorStatics$",{rd:1,b:1});var hb;function ib(){hb||(hb=new gb);return hb}function jb(){}jb.prototype=new A;jb.prototype.constructor=jb;jb.prototype.$classData=L({Vc:0},"scala.collection.package$$colon$plus$",{Vc:1,b:1});var kb;function lb(){}lb.prototype=new A;lb.prototype.constructor=lb;lb.prototype.$classData=L({Wc:0},"scala.collection.package$$plus$colon$",{Wc:1,b:1});var mb;function nb(){}nb.prototype=new A;
nb.prototype.constructor=nb;nb.prototype.$classData=L({Bc:0},"scala.math.Ordered$",{Bc:1,b:1});var ob;function pb(){this.sb=null;qb=this;rb||(rb=new sb);rb||(rb=new sb);tb||(tb=new ub);vb||(vb=new wb);xb();yb();this.sb=zb();Ab||(Ab=new Bb);mb||(mb=new lb);kb||(kb=new jb);Cb||(Cb=new Db);Eb();Fb();Gb||(Gb=new Hb);Ib||(Ib=new Jb);Kb||(Kb=new Lb);Mb||(Mb=new Nb);Ob||(Ob=new Pb);Qb||(Qb=new Rb);ob||(ob=new nb);Sb||(Sb=new Tb);Ub||(Ub=new Vb);Wb||(Wb=new Xb);Yb||(Yb=new Zb)}pb.prototype=new A;
pb.prototype.constructor=pb;pb.prototype.$classData=L({Dc:0},"scala.package$",{Dc:1,b:1});var qb;function $b(){}$b.prototype=new A;$b.prototype.constructor=$b;function ac(a,b,c){if(b===c)c=!0;else if(bc(b))a:if(bc(c))c=cc(b,c);else{if(c instanceof n){if("number"===typeof b){c=+b===w(c);break a}if(b instanceof v){a=null===b?m:b;b=a.l;c=w(c);c=a.m===c&&b===c>>31;break a}}c=null===b?null===c:ea(b,c)}else c=b instanceof n?dc(b,c):null===b?null===c:ea(b,c);return c}
function cc(a,b){if("number"===typeof a){a=+a;if("number"===typeof b)return a===+b;if(b instanceof v){var c=null===b?m:b;b=c.m;c=c.l;return a===ec(fc(),b,c)}return!1}if(a instanceof v){c=null===a?m:a;a=c.m;c=c.l;if(b instanceof v){b=null===b?m:b;var e=b.l;return a===b.m&&c===e}return"number"===typeof b?(b=+b,ec(fc(),a,c)===b):!1}return null===a?null===b:ea(a,b)}
function dc(a,b){if(b instanceof n)return w(a)===w(b);if(bc(b)){if("number"===typeof b)return+b===w(a);if(b instanceof v){b=null===b?m:b;var c=b.l;a=w(a);return b.m===a&&c===a>>31}return null===b?null===a:ea(b,a)}return null===a&&null===b}$b.prototype.$classData=L({Ad:0},"scala.runtime.BoxesRunTime$",{Ad:1,b:1});var gc;function hc(){gc||(gc=new $b);return gc}function ic(){}ic.prototype=new A;ic.prototype.constructor=ic;function jc(a){kc||(kc=new ic);var b=a.Qa();return cb(b,a.M()+"(",",")}
ic.prototype.$classData=L({Dd:0},"scala.runtime.ScalaRunTime$",{Dd:1,b:1});var kc;function T(){}T.prototype=new A;T.prototype.constructor=T;T.prototype.g=function(a,b){a=this.za(a,b);return-430675100+l(5,a<<13|a>>>19|0)|0};T.prototype.za=function(a,b){b=l(-862048943,b);b=l(461845907,b<<15|b>>>17|0);return a^b};T.prototype.t=function(a,b){a^=b;a=l(-2048144789,a^(a>>>16|0));a=l(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)};
function U(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{b=fc();if(-0x7fffffffffffffff>a){b.qa=-2147483648;var c=0}else if(0x7fffffffffffffff<=a)b.qa=2147483647,c=-1;else{c=a|0;var e=a/4294967296|0;b.qa=0>a&&0!==c?-1+e|0:e}b=b.qa;a=ec(fc(),c,b)===a?c^b:Ma(Na(),a)}return a}return b instanceof v?(a=null===b?m:b,b=new v(a.m,a.l),a=b.m,b=b.l,b===a>>31?a:a^b):fa(b)}
T.prototype.$classData=L({Gd:0},"scala.runtime.Statics$",{Gd:1,b:1});var lc;function V(){lc||(lc=new T);return lc}function mc(){}mc.prototype=new A;mc.prototype.constructor=mc;function nc(a){oc||(oc=new mc);return a instanceof pc?a.oa:a}mc.prototype.$classData=L({zd:0},"scala.scalajs.runtime.package$",{zd:1,b:1});var oc;function qc(a){this.tb=a}qc.prototype=new A;qc.prototype.constructor=qc;qc.prototype.i=function(){return"DynamicVariable("+this.tb+")"};
qc.prototype.$classData=L({Ec:0},"scala.util.DynamicVariable",{Ec:1,b:1});function rc(){}rc.prototype=new A;rc.prototype.constructor=rc;function sc(){}sc.prototype=rc.prototype;rc.prototype.g=function(a,b){a=this.za(a,b);return-430675100+l(5,a<<13|a>>>19|0)|0};rc.prototype.za=function(a,b){b=l(-862048943,b);b=l(461845907,b<<15|b>>>17|0);return a^b};rc.prototype.t=function(a,b){return tc(a^b)};function tc(a){a=l(-2048144789,a^(a>>>16|0));a=l(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}
function uc(a){0===(32&a.wa)<<24>>24&&0===(32&a.wa)<<24>>24&&(a.ib=new G(new Int32Array([1632,1776,1984,2406,2534,2662,2790,2918,3046,3174,3302,3430,3664,3792,3872,4160,4240,6112,6160,6470,6608,6784,6800,6992,7088,7232,7248,42528,43216,43264,43472,43600,44016,65296,66720,69734,69872,69942,70096,71360,120782,120792,120802,120812,120822])),a.wa=(32|a.wa)<<24>>24);return a.ib}function vc(){this.ib=null;this.wa=0}vc.prototype=new A;vc.prototype.constructor=vc;
vc.prototype.$classData=L({Zb:0},"java.lang.Character$",{Zb:1,b:1,c:1});var wc;function xc(a){throw new yc('For input string: "'+a+'"');}function zc(){}zc.prototype=new A;zc.prototype.constructor=zc;
function Fa(a,b){a=null===b?0:b.length|0;0===a&&xc(b);var c=65535&(b.charCodeAt(0)|0),e=45===c,d=e?2147483648:2147483647;c=e||43===c?1:0;c>=(b.length|0)&&xc(b);for(var k=0;c!==a;){wc||(wc=new vc);var h=wc;var f=65535&(b.charCodeAt(c)|0);if(256>f)h=48<=f&&57>=f?-48+f|0:65<=f&&90>=f?-55+f|0:97<=f&&122>=f?-87+f|0:-1;else if(65313<=f&&65338>=f)h=-65303+f|0;else if(65345<=f&&65370>=f)h=-65335+f|0;else{var r=uc(h);$a||($a=new Za);a:for(var p=f,q=0,u=r.a.length;;){if(q===u){r=-1-q|0;break a}var z=(q+u|0)>>>
1|0,D=r.a[z];if(p<D)u=z;else{if(ac(hc(),p,D)){r=z;break a}q=1+z|0}}r=0>r?-2-r|0:r;0>r?h=-1:(h=f-uc(h).a[r]|0,h=9<h?-1:h)}h=10>h?h:-1;k=10*k+h;(-1===h||k>d)&&xc(b);c=1+c|0}return e?-k|0:k|0}zc.prototype.$classData=L({cc:0},"java.lang.Integer$",{cc:1,b:1,c:1});var Ac;function Ga(){Ac||(Ac=new zc);return Ac}function Bc(){}Bc.prototype=new A;Bc.prototype.constructor=Bc;function Cc(){}Cc.prototype=Bc.prototype;function bc(a){return a instanceof Bc||"number"===typeof a}
function Dc(a,b){a.mb=b;a.lc=null;a.mc=!0;a.nc=!0;a.gb()}
class Ec extends Error{constructor(){super();this.lc=this.mb=null;this.nc=this.mc=!1}ua(){return this.mb}gb(){"[object Error]"!==Object.prototype.toString.call(this)&&void 0!==Error.captureStackTrace&&Error.captureStackTrace(this)}i(){var a=da(this),b=this.ua();return null===b?a:a+": "+b}w(){return x.prototype.w.call(this)}s(a){return x.prototype.s.call(this,a)}get ["message"](){var a=this.ua();return null===a?"":a}get ["name"](){return da(this)}["toString"](){return this.i()}}
L({Tb:0},"org.getshaka.shaka.RootBinding",{Tb:1,b:1,Kd:1});
function Fc(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+ba(1E9)|0)-(0!==b?ba(b):32+ba(a)|0)|0,e=c,d=0===(32&e)?1E9<<e:0;e=0===(32&e)?5E8>>>(31-e|0)|0|0<<e:1E9<<e;var k=a,h=b;for(a=b=0;0<=c&&0!==(-2097152&h);){var f=k,r=h,p=d,q=e;if(r===q?(-2147483648^f)>=(-2147483648^p):(-2147483648^r)>=(-2147483648^q))f=h,r=e,h=k-d|0,f=(-2147483648^h)>(-2147483648^k)?-1+(f-r|0)|0:f-r|0,k=h,h=f,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;f=e>>>1|0;d=d>>>1|0|e<<31;e=f}c=h;if(0===c?-1147483648<=(-2147483648^
k):-2147483648<=(-2147483648^c))c=4294967296*h+ +(k>>>0),k=c/1E9,d=k/4294967296|0,e=b,b=k=e+(k|0)|0,a=(-2147483648^k)<(-2147483648^e)?1+(a+d|0)|0:a+d|0,k=c%1E9|0;c=""+k;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}function Gc(){this.qa=0}Gc.prototype=new A;Gc.prototype.constructor=Gc;function ec(a,b,c){return 0>c?-(4294967296*+((0!==b?~c:-c|0)>>>0)+ +((-b|0)>>>0)):4294967296*c+ +(b>>>0)}
Gc.prototype.$classData=L({Vb:0},"org.scalajs.linker.runtime.RuntimeLong$",{Vb:1,b:1,c:1});var Hc;function fc(){Hc||(Hc=new Gc);return Hc}function Ic(){this.ob=null;Jc=this;this.ob=new qc(Ra().kb);Ra()}Ic.prototype=new A;Ic.prototype.constructor=Ic;Ic.prototype.$classData=L({tc:0},"scala.Console$",{tc:1,b:1,Sd:1});var Jc;function Bb(){}Bb.prototype=new A;Bb.prototype.constructor=Bb;Bb.prototype.i=function(){return"::"};
Bb.prototype.$classData=L({Yc:0},"scala.collection.immutable.$colon$colon$",{Yc:1,b:1,c:1});var Ab;function Jb(){}Jb.prototype=new A;Jb.prototype.constructor=Jb;Jb.prototype.$classData=L({ld:0},"scala.collection.immutable.Range$",{ld:1,b:1,c:1});var Ib;function Hb(){}Hb.prototype=new A;Hb.prototype.constructor=Hb;Hb.prototype.$classData=L({td:0},"scala.collection.mutable.StringBuilder$",{td:1,b:1,c:1});var Gb;function Nb(){}Nb.prototype=new A;Nb.prototype.constructor=Nb;
Nb.prototype.$classData=L({yc:0},"scala.math.Fractional$",{yc:1,b:1,c:1});var Mb;function Pb(){}Pb.prototype=new A;Pb.prototype.constructor=Pb;Pb.prototype.$classData=L({zc:0},"scala.math.Integral$",{zc:1,b:1,c:1});var Ob;function Rb(){}Rb.prototype=new A;Rb.prototype.constructor=Rb;Rb.prototype.$classData=L({Ac:0},"scala.math.Numeric$",{Ac:1,b:1,c:1});var Qb;function Kc(){}Kc.prototype=new A;Kc.prototype.constructor=Kc;function Lc(){}Lc.prototype=Kc.prototype;Kc.prototype.i=function(){return"\x3cfunction0\x3e"};
function Mc(a){this.ab=a}Mc.prototype=new A;Mc.prototype.constructor=Mc;Mc.prototype.i=function(){return""+this.ab};Mc.prototype.$classData=L({Bd:0},"scala.runtime.IntRef",{Bd:1,b:1,c:1});function Nc(a){this.bb=a}Nc.prototype=new A;Nc.prototype.constructor=Nc;Nc.prototype.i=function(){return""+this.bb};Nc.prototype.$classData=L({Cd:0},"scala.runtime.ObjectRef",{Cd:1,b:1,c:1});
var ua=L({vd:0},"scala.scalajs.js.Dynamic",{vd:1,b:1,te:1},function(){throw new TypeError("Cannot call isInstance() on a Class representing a JS trait/object");});function Vb(){}Vb.prototype=new A;Vb.prototype.constructor=Vb;Vb.prototype.$classData=L({Fc:0},"scala.util.Either$",{Fc:1,b:1,c:1});var Ub;function Xb(){}Xb.prototype=new A;Xb.prototype.constructor=Xb;Xb.prototype.i=function(){return"Left"};Xb.prototype.$classData=L({Gc:0},"scala.util.Left$",{Gc:1,b:1,c:1});var Wb;function Zb(){}
Zb.prototype=new A;Zb.prototype.constructor=Zb;Zb.prototype.i=function(){return"Right"};Zb.prototype.$classData=L({Hc:0},"scala.util.Right$",{Hc:1,b:1,c:1});var Yb;function Oc(){this.ub=this.Ba=0;Pc=this;this.Ba=y("Seq");this.ub=y("Map");y("Set");qb||(qb=new pb);for(var a=this.ub,b=0,c=0,e=0,d=1,k=qb.sb.o();k.j();){var h=k.k();h=U(V(),h);b=b+h|0;c^=h;d=l(d,1|h);e=1+e|0}a=this.g(a,b);a=this.g(a,c);a=this.za(a,d);this.t(a,e)}Oc.prototype=new sc;Oc.prototype.constructor=Oc;
Oc.prototype.$classData=L({Ic:0},"scala.util.hashing.MurmurHash3$",{Ic:1,Vd:1,b:1});var Pc;function Qc(){Pc||(Pc=new Oc);return Pc}function wa(){Rc||(Rc=new Sc);return Tc}function Sc(){Rc=this;Tc=new Vc(1,"Empty")}Sc.prototype=new A;Sc.prototype.constructor=Sc;Sc.prototype.$classData=L({Lb:0},"SquareState$",{Lb:1,b:1,wc:1,Rd:1});var Rc;class Wc extends Ec{}function Xc(){}Xc.prototype=new A;Xc.prototype.constructor=Xc;function Yc(){}Yc.prototype=Xc.prototype;
function Zc(){this.U=null;$c=this;this.U=new W}Zc.prototype=new A;Zc.prototype.constructor=Zc;Zc.prototype.$classData=L({Oc:0},"scala.collection.Iterator$",{Oc:1,b:1,E:1,c:1});var $c;function xb(){$c||($c=new Zc);return $c}function ad(){}ad.prototype=new A;ad.prototype.constructor=ad;ad.prototype.B=function(){throw new bd("head of empty lazy list");};function cd(){throw new dd("tail of empty lazy list");}
ad.prototype.$classData=L({dd:0},"scala.collection.immutable.LazyList$State$Empty$",{dd:1,b:1,ee:1,c:1});var ed;function fd(){ed||(ed=new ad);return ed}function Lb(){}Lb.prototype=new A;Lb.prototype.constructor=Lb;Lb.prototype.$classData=L({xc:0},"scala.math.Equiv$",{xc:1,b:1,Td:1,c:1});var Kb;function Tb(){}Tb.prototype=new A;Tb.prototype.constructor=Tb;Tb.prototype.$classData=L({Cc:0},"scala.math.Ordering$",{Cc:1,b:1,Ud:1,c:1});var Sb;function gd(){}gd.prototype=new A;gd.prototype.constructor=gd;
function Aa(a,b){return(c=>()=>hd(c))(b)}gd.prototype.$classData=L({ud:0},"scala.scalajs.js.Any$",{ud:1,b:1,ue:1,ve:1});var id;function Ba(){id||(id=new gd);return id}function Q(a){this.yd=a}Q.prototype=new Lc;Q.prototype.constructor=Q;function hd(a){return(0,a.yd)()}Q.prototype.$classData=L({xd:0},"scala.scalajs.runtime.AnonFunction0",{xd:1,we:1,b:1,Hd:1});function jd(){}jd.prototype=new A;jd.prototype.constructor=jd;function kd(){}kd.prototype=jd.prototype;
function ha(a){a=+a;return Ma(Na(),a)}class X extends Wc{}X.prototype.$classData=L({C:0},"java.lang.RuntimeException",{C:1,I:1,J:1,b:1,c:1});function y(a){for(var b=0,c=1,e=-1+(a.length|0)|0;0<=e;)b=b+l(65535&(a.charCodeAt(e)|0),c)|0,c=l(31,c),e=-1+e|0;return b}var ld=L({Wb:0},"java.lang.String",{Wb:1,b:1,c:1,$b:1,hb:1},a=>"string"===typeof a);function eb(a){a.f="";return a}function S(){this.f=null}S.prototype=new A;S.prototype.constructor=S;S.prototype.i=function(){return this.f};
S.prototype.h=function(){return this.f.length|0};S.prototype.$classData=L({ic:0},"java.lang.StringBuilder",{ic:1,b:1,hb:1,Xb:1,c:1});function v(a,b){this.m=a;this.l=b}v.prototype=new Cc;v.prototype.constructor=v;v.prototype.s=function(a){return a instanceof v?this.m===a.m&&this.l===a.l:!1};v.prototype.w=function(){return this.m^this.l};v.prototype.i=function(){fc();var a=this.m,b=this.l;return b===a>>31?""+a:0>b?"-"+Fc(-a|0,0!==a?~b:-b|0):Fc(a,b)};
v.prototype.$classData=L({Ub:0},"org.scalajs.linker.runtime.RuntimeLong",{Ub:1,Od:1,b:1,c:1,$b:1});function md(){}md.prototype=new A;md.prototype.constructor=md;function nd(){}g=nd.prototype=md.prototype;g.o=function(){return this};g.e=function(){return!this.j()};g.ta=function(a){for(var b=0;b<a&&this.j();)this.k(),b=1+b|0;return this};g.i=function(){return"\x3citerator\x3e"};g.ra=function(a,b,c,e){return fb(this,a,b,c,e)};g.x=function(){return-1};function sb(){od||(od=new pd)}sb.prototype=new Yc;
sb.prototype.constructor=sb;sb.prototype.$classData=L({Mc:0},"scala.collection.Iterable$",{Mc:1,Nc:1,b:1,E:1,c:1});var rb;function qd(){}qd.prototype=new A;qd.prototype.constructor=qd;function rd(){}rd.prototype=qd.prototype;function sd(a,b){var c=a.x();if(-1!==c){var e=b.x();c=-1!==e&&c!==e}else c=!1;if(c)return!1;a:{a=a.o();for(b=b.o();a.j()&&b.j();)if(!ac(hc(),a.k(),b.k())){b=!1;break a}b=a.j()===b.j()}return b}function pd(){yb()}pd.prototype=new Yc;pd.prototype.constructor=pd;
pd.prototype.$classData=L({$c:0},"scala.collection.immutable.Iterable$",{$c:1,Nc:1,b:1,E:1,c:1});var od;function td(){this.Bb=null;ud=this;this.Bb=vd(new wd(new Q((()=>()=>fd())(this))))}td.prototype=new A;td.prototype.constructor=td;function xd(a,b,c){return new wd(new Q(((e,d,k)=>()=>{for(var h=d.bb,f=k.ab;0<f&&!h.e();)h=cd(Y(h)),d.bb=h,f=-1+f|0,k.ab=f;return Y(h)})(a,new Nc(b),new Mc(c))))}td.prototype.$classData=L({bd:0},"scala.collection.immutable.LazyList$",{bd:1,b:1,ka:1,E:1,c:1});var ud;
function Eb(){ud||(ud=new td);return ud}function Db(){}Db.prototype=new A;Db.prototype.constructor=Db;Db.prototype.$classData=L({nd:0},"scala.collection.immutable.Stream$",{nd:1,b:1,ka:1,E:1,c:1});var Cb;function yd(){}yd.prototype=new A;yd.prototype.constructor=yd;function zd(){}zd.prototype=yd.prototype;yd.prototype.Qa=function(){return new Ad(this)};var va=L({pa:0},"SquareState",{pa:1,b:1,D:1,ga:1,c:1,Ta:1});yd.prototype.$classData=va;function Bd(){}Bd.prototype=new kd;
Bd.prototype.constructor=Bd;function Cd(){}Cd.prototype=Bd.prototype;class Dd extends X{}class Z extends X{constructor(a){super();Dc(this,a)}}Z.prototype.$classData=L({bc:0},"java.lang.IndexOutOfBoundsException",{bc:1,C:1,I:1,J:1,b:1,c:1});L({ec:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{ec:1,Rb:1,b:1,Pb:1,Yb:1,Qb:1});L({gc:0},"java.lang.NullPointerException",{gc:1,C:1,I:1,J:1,b:1,c:1});class dd extends X{constructor(a){super();Dc(this,a)}}
dd.prototype.$classData=L({oc:0},"java.lang.UnsupportedOperationException",{oc:1,C:1,I:1,J:1,b:1,c:1});class bd extends X{constructor(a){super();Dc(this,a)}}bd.prototype.$classData=L({sc:0},"java.util.NoSuchElementException",{sc:1,C:1,I:1,J:1,b:1,c:1});
class P extends X{constructor(a){super();this.pb=null;this.Ra=!1;this.Aa=a;Dc(this,null)}ua(){if(!this.Ra&&!this.Ra){if(null===this.Aa)var a="null";else try{a=ia(this.Aa)+" (of class "+da(this.Aa)+")"}catch(b){if(oc||(oc=new mc),null!==(b instanceof Ec?b:new pc(b)))a="an instance of class "+da(this.Aa);else throw b;}this.pb=a;this.Ra=!0}return this.pb}}P.prototype.$classData=L({uc:0},"scala.MatchError",{uc:1,C:1,I:1,J:1,b:1,c:1});
function Ad(a){this.rb=this.ha=0;this.qb=null;if(null===a)throw nc(null);this.qb=a;this.ha=0;this.rb=a.K()}Ad.prototype=new nd;Ad.prototype.constructor=Ad;Ad.prototype.j=function(){return this.ha<this.rb};Ad.prototype.k=function(){var a=this.qb.L(this.ha);this.ha=1+this.ha|0;return a};Ad.prototype.$classData=L({vc:0},"scala.Product$$anon$1",{vc:1,Ea:1,b:1,ja:1,y:1,z:1});function W(){}W.prototype=new nd;W.prototype.constructor=W;W.prototype.j=function(){return!1};W.prototype.x=function(){return 0};
W.prototype.k=function(){throw new bd("next on empty iterator");};W.prototype.$classData=L({Pc:0},"scala.collection.Iterator$$anon$19",{Pc:1,Ea:1,b:1,ja:1,y:1,z:1});function Ed(a,b){if(0>b)throw new Z(""+b);a=a.fb(b);if(a.e())throw new Z(""+b);return a.va()}function Fd(a,b){if(b&&b.$classData&&b.$classData.q.xb)a:for(;;){if(a===b){a=!0;break a}if((a.e()?0:!b.e())&&ac(hc(),a.va(),b.va()))a=a.Z(),b=b.Z();else{a=a.e()&&b.e();break a}}else a=sd(a,b);return a}function wb(){Fb()}wb.prototype=new rd;
wb.prototype.constructor=wb;wb.prototype.$classData=L({Zc:0},"scala.collection.immutable.IndexedSeq$",{Zc:1,Rc:1,b:1,ka:1,E:1,c:1});var vb;function Gd(a){this.Wa=a}Gd.prototype=new nd;Gd.prototype.constructor=Gd;Gd.prototype.j=function(){return!this.Wa.e()};Gd.prototype.k=function(){if(this.Wa.e())return xb().U.k();Y(this.Wa).B()};Gd.prototype.$classData=L({cd:0},"scala.collection.immutable.LazyList$LazyIterator",{cd:1,Ea:1,b:1,ja:1,y:1,z:1});function Hd(){Id=this;zb();zb()}Hd.prototype=new A;
Hd.prototype.constructor=Hd;Hd.prototype.$classData=L({gd:0},"scala.collection.immutable.List$",{gd:1,b:1,Tc:1,ka:1,E:1,c:1});var Id;function yb(){Id||(Id=new Hd)}
function Jd(a){a.p<=a.n&&xb().U.k();a.na=1+a.na|0;for(var b=null;0===b.a.length;)a.na=1+a.na|0,b=null;a.La=a.W;var c=a.jd/2|0,e=a.na-c|0;a.S=(1+c|0)-(0>e?-e|0:e)|0;c=a.S;switch(c){case 1:a.F=b;break;case 2:a.P=b;break;case 3:a.Q=b;break;case 4:a.R=b;break;case 5:a.V=b;break;case 6:a.Za=b;break;default:throw new P(c);}a.W=a.La+l(b.a.length,1<<l(5,-1+a.S|0))|0;a.W>a.G&&(a.W=a.G);1<a.S&&(a.ma=-1+(1<<l(5,a.S))|0)}
function Kd(a,b,c){this.Za=this.V=this.R=this.Q=this.P=null;this.G=b;this.jd=c;this.F=a.X;this.O=this.F.a.length;this.ma=this.n=0;this.p=this.G;this.na=0;this.S=1;this.La=0;this.W=this.O}Kd.prototype=new A;Kd.prototype.constructor=Kd;g=Kd.prototype;g.o=function(){return this};g.e=function(){return this.p<=this.n};g.i=function(){return"\x3citerator\x3e"};g.ra=function(a,b,c,e){return fb(this,a,b,c,e)};g.x=function(){return this.p-this.n|0};g.j=function(){return this.p>this.n};
g.k=function(){if(this.n===this.O){var a=(this.n-this.p|0)+this.G|0;a===this.W&&Jd(this);if(1<this.S){a=a-this.La|0;var b=this.ma^a;1024>b?this.F=this.P.a[31&(a>>>5|0)]:(32768>b?this.P=this.Q.a[31&(a>>>10|0)]:(1048576>b?this.Q=this.R.a[31&(a>>>15|0)]:(33554432>b?this.R=this.V.a[31&(a>>>20|0)]:(this.V=this.Za.a[a>>>25|0],this.R=this.V.a[0]),this.Q=this.R.a[0]),this.P=this.Q.a[0]),this.F=this.P.a[0]);this.ma=a}this.p=this.p-this.n|0;a=this.F.a.length;b=this.p;this.O=a<b?a:b;this.n=0}a=this.F.a[this.n];
this.n=1+this.n|0;return a};
g.ta=function(a){if(0<a){a=((this.n-this.p|0)+this.G|0)+a|0;var b=this.G;a=a<b?a:b;if(a===this.G)this.O=this.p=this.n=0;else{for(;a>=this.W;)Jd(this);b=a-this.La|0;if(1<this.S){var c=this.ma^b;1024>c||(32768>c||(1048576>c||(33554432>c||(this.V=this.Za.a[b>>>25|0]),this.R=this.V.a[31&(b>>>20|0)]),this.Q=this.R.a[31&(b>>>15|0)]),this.P=this.Q.a[31&(b>>>10|0)]);this.F=this.P.a[31&(b>>>5|0)];this.ma=b}this.O=this.F.a.length;this.n=31&b;this.p=this.n+(this.G-a|0)|0;this.O>this.p&&(this.O=this.p)}}return this};
g.$classData=L({hd:0},"scala.collection.immutable.NewVectorIterator",{hd:1,b:1,ja:1,y:1,z:1,Oa:1});function ub(){yb()}ub.prototype=new rd;ub.prototype.constructor=ub;ub.prototype.$classData=L({md:0},"scala.collection.immutable.Seq$",{md:1,Rc:1,b:1,ka:1,E:1,c:1});var tb;function Ld(){this.$a=0;this.Gb=null;Md=this;try{var a=Ua;Ta||(Ta=new Sa);var b=a(Ta,"scala.collection.immutable.Vector.defaultApplyPreferredMaxLength","250");var c=Fa(Ga(),b)}catch(e){throw e;}this.$a=c;this.Gb=new Kd(Nd(),0,0)}
Ld.prototype=new A;Ld.prototype.constructor=Ld;Ld.prototype.$classData=L({pd:0},"scala.collection.immutable.Vector$",{pd:1,b:1,Tc:1,ka:1,E:1,c:1});var Md;function Fb(){Md||(Md=new Ld);return Md}function Od(a){this.Ib=0;this.Fd=a;this.Ma=0;this.Ib=a.K()}Od.prototype=new nd;Od.prototype.constructor=Od;Od.prototype.j=function(){return this.Ma<this.Ib};Od.prototype.k=function(){var a=this.Fd.L(this.Ma);this.Ma=1+this.Ma|0;return a};
Od.prototype.$classData=L({Ed:0},"scala.runtime.ScalaRunTime$$anon$1",{Ed:1,Ea:1,b:1,ja:1,y:1,z:1});function Ha(a){this.aa=a}Ha.prototype=new zd;Ha.prototype.constructor=Ha;g=Ha.prototype;g.w=function(){var a=y("Set");a=V().g(-889275714,a);var b=this.aa;a=V().g(a,b);return V().t(a,1)};g.s=function(a){return this===a?!0:a instanceof Ha?this.aa===a.aa:!1};g.i=function(){return jc(this)};g.K=function(){return 1};g.M=function(){return"Set"};g.L=function(a){if(0===a)return this.aa;throw new Z(""+a);};
g.$classData=L({Nb:0},"SquareState$Set",{Nb:1,pa:1,b:1,D:1,ga:1,c:1,Ta:1});function R(a){this.$=a}R.prototype=new zd;R.prototype.constructor=R;g=R.prototype;g.w=function(){var a=y("SetByUser");a=V().g(-889275714,a);var b=this.$;a=V().g(a,b);return V().t(a,1)};g.s=function(a){return this===a?!0:a instanceof R?this.$===a.$:!1};g.i=function(){return jc(this)};g.K=function(){return 1};g.M=function(){return"SetByUser"};g.L=function(a){if(0===a)return this.$;throw new Z(""+a);};
g.$classData=L({Ob:0},"SquareState$SetByUser",{Ob:1,pa:1,b:1,D:1,ga:1,c:1,Ta:1});class yc extends Dd{constructor(a){super();Dc(this,a)}}yc.prototype.$classData=L({hc:0},"java.lang.NumberFormatException",{hc:1,Nd:1,C:1,I:1,J:1,b:1,c:1});function Pd(){}Pd.prototype=new A;Pd.prototype.constructor=Pd;function Qd(){}Qd.prototype=Pd.prototype;Pd.prototype.sa=function(){return this.Y()};Pd.prototype.ra=function(a,b,c,e){return fb(this,a,b,c,e)};function Rd(a){this.N=0;this.Lc=a;this.ia=0;this.N=a.h()}
Rd.prototype=new nd;Rd.prototype.constructor=Rd;g=Rd.prototype;g.x=function(){return this.N};g.j=function(){return 0<this.N};g.k=function(){if(this.j()){var a=this.Lc.v(this.ia);this.ia=1+this.ia|0;this.N=-1+this.N|0;return a}return xb().U.k()};g.ta=function(a){0<a&&(this.ia=this.ia+a|0,a=this.N-a|0,this.N=0>a?0:a);return this};g.$classData=L({Kc:0},"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{Kc:1,Ea:1,b:1,ja:1,y:1,z:1,c:1});function Sd(){}Sd.prototype=new Cd;
Sd.prototype.constructor=Sd;function Td(){}Td.prototype=Sd.prototype;
class pc extends X{constructor(a){super();this.oa=a;Dc(this,null)}ua(){return ia(this.oa)}gb(){}M(){return"JavaScriptException"}K(){return 1}L(a){if(0===a)a=this.oa;else throw V(),new Z(""+a);return a}Qa(){return new Od(this)}w(){var a=Qc();var b=this.K();if(0===b)a=y(this.M());else{var c=a.g(-889275714,y(this.M()));for(var e=0;e<b;){var d=this.L(e);c=a.g(c,U(V(),d));e=1+e|0}a=a.t(c,b)}return a}s(a){if(this===a)return!0;if(a instanceof pc){var b=this.oa;a=a.oa;return ac(hc(),b,a)}return!1}}
pc.prototype.$classData=L({wd:0},"scala.scalajs.js.JavaScriptException",{wd:1,C:1,I:1,J:1,b:1,c:1,ga:1,D:1});function Qa(a){this.fc=a;this.ya=""}Qa.prototype=new Td;Qa.prototype.constructor=Qa;function Ja(){Jc||(Jc=new Ic);var a=Jc.ob.tb;for(var b="solved\n";""!==b;){var c=b.indexOf("\n")|0;if(0>c)a.ya=""+a.ya+b,b="";else{var e=""+a.ya+b.substring(0,c);"undefined"!==typeof console&&(a.fc&&console.error?console.error(e):console.log(e));a.ya="";b=b.substring(1+c|0)}}}
Qa.prototype.$classData=L({dc:0},"java.lang.JSConsoleBasedPrintStream",{dc:1,Jd:1,Id:1,Rb:1,b:1,Pb:1,Yb:1,Qb:1,Xb:1});function Ud(){}Ud.prototype=new Qd;Ud.prototype.constructor=Ud;function Vd(){}Vd.prototype=Ud.prototype;Ud.prototype.i=function(){return this.Y()+"(\x3cnot computed\x3e)"};function Vc(a,b){this.cb=b}Vc.prototype=new zd;Vc.prototype.constructor=Vc;g=Vc.prototype;g.K=function(){return 0};g.L=function(a){throw new Z(""+a);};g.M=function(){return this.cb};g.i=function(){return this.cb};
g.$classData=L({Mb:0},"SquareState$$anon$1",{Mb:1,pa:1,b:1,D:1,ga:1,c:1,Ta:1,xe:1,wc:1,Pd:1,Qd:1});function Wd(a,b){return a===b?!0:b&&b.$classData&&b.$classData.q.Ia&&b.eb(a)?a.Ca(b):!1}function Xd(){}Xd.prototype=new Qd;Xd.prototype.constructor=Xd;function Yd(){}g=Yd.prototype=Xd.prototype;g.eb=function(){return!0};g.s=function(a){return Wd(this,a)};
g.w=function(){var a=Qc();if(this&&this.$classData&&this.$classData.q.vb)a:{var b=a.Ba,c=this.h();switch(c){case 0:a=a.t(b,0);break a;case 1:c=b;b=this.v(0);a=a.t(a.g(c,U(V(),b)),1);break a;default:var e=this.v(0),d=U(V(),e);e=b=a.g(b,d);var k=this.v(1);k=U(V(),k);var h=k-d|0;for(d=2;d<c;){b=a.g(b,k);var f=this.v(d);f=U(V(),f);if(h!==(f-k|0)){b=a.g(b,f);for(d=1+d|0;d<c;)e=this.v(d),b=a.g(b,U(V(),e)),d=1+d|0;a=a.t(b,c);break a}k=f;d=1+d|0}a=tc(a.g(a.g(e,h),k))}}else if(this instanceof Zd){for(c=a.Ba;!this.e();)this.B();
a=a.t(c,0)}else a:if(b=a.Ba,c=this.o(),c.j())if(e=c.k(),c.j()){d=c.k();h=U(V(),e);e=b=a.g(b,h);k=U(V(),d);h=k-h|0;for(d=2;c.j();){b=a.g(b,k);f=c.k();f=U(V(),f);if(h!==(f-k|0)){b=a.g(b,f);for(d=1+d|0;c.j();)e=c.k(),b=a.g(b,U(V(),e)),d=1+d|0;a=a.t(b,d);break a}k=f;d=1+d|0}a=tc(a.g(a.g(e,h),k))}else a=a.t(a.g(b,U(V(),e)),1);else a=a.t(b,0);return a};g.i=function(){return cb(this,this.sa()+"(",", ")};g.e=function(){return 0===this.fa(0)};g.Ca=function(a){return sd(this,a)};function $d(){}
$d.prototype=new Vd;$d.prototype.constructor=$d;function ae(){}ae.prototype=$d.prototype;function be(){this.Ka=null}be.prototype=new ae;be.prototype.constructor=be;function ce(){}ce.prototype=be.prototype;be.prototype.v=function(a){return this.Ka.v(a)};be.prototype.h=function(){return this.Ka.h()};be.prototype.e=function(){return this.Ka.e()};function de(a){this.Ka=a}de.prototype=new ce;de.prototype.constructor=de;g=de.prototype;g.o=function(){return new Rd(this)};g.Y=function(){return"IndexedSeqView"};
g.fa=function(a){var b=this.h();return b===a?0:b<a?-1:1};g.x=function(){return this.h()};g.$classData=L({Jc:0},"scala.collection.IndexedSeqView$Id",{Jc:1,$d:1,Wd:1,Xd:1,Da:1,b:1,Fa:1,y:1,Ha:1,z:1,Ga:1,be:1,c:1,Zd:1,Ja:1,Yd:1,wb:1});function ee(){}ee.prototype=new Yd;ee.prototype.constructor=ee;function fe(){}fe.prototype=ee.prototype;function ge(){}ge.prototype=new Yd;ge.prototype.constructor=ge;function he(){}he.prototype=ge.prototype;
function ie(a,b,c,e){b.f=""+b.f+c;a.la?a.e()||Y(a).B():b.f+="\x3cnot computed\x3e";b.f=""+b.f+e;return b}function wd(a){this.Db=null;this.Xa=!1;this.Cb=a;this.Ya=this.la=!1}wd.prototype=new fe;wd.prototype.constructor=wd;g=wd.prototype;g.Y=function(){return"LinearSeq"};g.h=function(){for(var a=this,b=0;!a.e();)b=1+b|0,a=a.Z();return b};g.fa=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.e()?0:1;break a}if(b.e()){a=-1;break a}c=1+c|0;b=b.Z()}return a};
g.v=function(a){return Ed(this,a)};g.Ca=function(a){return Fd(this,a)};function Y(a){if(!a.Xa&&!a.Xa){if(a.Ya)throw a=new X,Dc(a,"self-referential LazyList or a derivation thereof has no more elements"),nc(a);a.Ya=!0;try{var b=hd(a.Cb)}finally{a.Ya=!1}a.la=!0;a.Cb=null;a.Db=b;a.Xa=!0}return a.Db}g.e=function(){return Y(this)===fd()};g.x=function(){return this.la&&this.e()?0:-1};g.va=function(){Y(this).B()};
function vd(a){var b=a,c=a;for(b.e()||(b=cd(Y(b)));c!==b&&!b.e();){b=cd(Y(b));if(b.e())break;b=cd(Y(b));if(b===c)break;c=cd(Y(c))}return a}g.o=function(){return this.la&&this.e()?xb().U:new Gd(this)};g.sa=function(){return"LazyList"};g.ra=function(a,b,c,e){vd(this);ie(this,a.A,b,e);return a};g.i=function(){var a=new S;eb(a);a.f="LazyList";return ie(this,a,"(",")").f};g.fb=function(a){return 0>=a?this:this.la&&this.e()?Eb().Bb:xd(Eb(),this,a)};g.Z=function(){return cd(Y(this))};
g.$classData=L({ad:0},"scala.collection.immutable.LazyList",{ad:1,yb:1,Ua:1,Da:1,b:1,Fa:1,y:1,Ha:1,z:1,Ga:1,Ia:1,Sa:1,Na:1,Ja:1,D:1,Eb:1,Ab:1,Fb:1,ed:1,xb:1,Qc:1,fd:1,c:1});function je(){this.X=null}je.prototype=new fe;je.prototype.constructor=je;function ke(){}g=ke.prototype=je.prototype;g.eb=function(a){return a&&a.$classData&&a.$classData.q.zb?this.h()===a.h():!0};
g.Ca=function(a){if(a&&a.$classData&&a.$classData.q.zb)if(this===a)var b=!0;else{var c=this.h();if(b=c===a.h()){var e=0,d=Fb().$a,k=Fb().$a;d=d<k?d:k;k=c>>31;var h=d>>>31|0|d>>31<<1;for(d=(k===h?(-2147483648^c)>(-2147483648^d<<1):k>h)?d:c;e<d&&b;)hc(),ne(e),b=ac(0,void 0,ne(e)),e=1+e|0;if(e<c&&b)for(c=this.o().ta(e),a=a.o().ta(e);b&&c.j();)b=ac(hc(),c.k(),a.k())}}else b=sd(this,a);return b};g.Y=function(){return"IndexedSeq"};g.fa=function(a){var b=this.h();return b===a?0:b<a?-1:1};g.x=function(){return this.h()};
g.h=function(){return this instanceof oe?this.Va:this.X.a.length};g.o=function(){return Nd()===this?Fb().Gb:new Kd(this,this.h(),0)};g.sa=function(){return"Vector"};function Zd(){}Zd.prototype=new fe;Zd.prototype.constructor=Zd;function pe(){}g=pe.prototype=Zd.prototype;g.Y=function(){return"LinearSeq"};g.v=function(a){return Ed(this,a)};g.Ca=function(a){return Fd(this,a)};g.e=function(){return this===zb()};g.h=function(){for(var a=0;!this.e();)a=1+a|0,qe();return a};
g.fa=function(a){if(0>a)a=1;else a:for(;;){if(0===a){a=this.e()?0:1;break a}if(this.e()){a=-1;break a}qe()}return a};g.sa=function(){return"List"};g.s=function(a){if(a instanceof Zd)a:for(;;){if(this===a){a=!0;break a}var b=this.e(),c=a.e();if(b||c)e=!1;else{hc();this.B();var e=ac(0,void 0,a.B())}if(e)qe();else{a=b&&c;break a}}else a=Wd(this,a);return a};g.fb=function(a){a:for(var b=this;;){if(0>=a||b.e())break a;a=-1+a|0;b=b.Z()}return b};function re(){this.X=null}re.prototype=new ke;
re.prototype.constructor=re;function se(){}se.prototype=re.prototype;function oe(){this.X=null;this.Va=0}oe.prototype=new se;oe.prototype.constructor=oe;function te(){}te.prototype=oe.prototype;function ue(){ve=this;zb();zb()}ue.prototype=new pe;ue.prototype.constructor=ue;g=ue.prototype;g.B=function(){throw new bd("head of empty list");};function qe(){throw new dd("tail of empty list");}g.x=function(){return 0};g.o=function(){return xb().U};g.M=function(){return"Nil"};g.K=function(){return 0};
g.L=function(a){V();throw new Z(""+a);};g.Qa=function(){return new Od(this)};g.Z=function(){qe()};g.va=function(){this.B()};g.$classData=L({kd:0},"scala.collection.immutable.Nil$",{kd:1,fe:1,yb:1,Ua:1,Da:1,b:1,Fa:1,y:1,Ha:1,z:1,Ga:1,Ia:1,Sa:1,Na:1,Ja:1,D:1,Eb:1,Ab:1,Fb:1,ed:1,xb:1,Qc:1,fd:1,ae:1,Uc:1,Sc:1,od:1,Xc:1,c:1,ga:1});var ve;function zb(){ve||(ve=new ue);return ve}function we(){this.X=null;this.Va=0;var a=ib().Hb;ib();this.Va=0;this.X=a}we.prototype=new te;we.prototype.constructor=we;
function ne(a){throw new Z(a+" is out of bounds (empty vector)");}we.prototype.s=function(a){return this===a||!(a instanceof je)&&Wd(this,a)};we.prototype.v=function(a){ne(a)};we.prototype.$classData=L({qd:0},"scala.collection.immutable.Vector0$",{qd:1,ce:1,he:1,ge:1,yb:1,Ua:1,Da:1,b:1,Fa:1,y:1,Ha:1,z:1,Ga:1,Ia:1,Sa:1,Na:1,Ja:1,D:1,Eb:1,Ab:1,Fb:1,zb:1,vb:1,wb:1,de:1,od:1,Uc:1,Sc:1,Xc:1,c:1});var xe;function Nd(){xe||(xe=new we);return xe}function db(){this.A=null}db.prototype=new he;
db.prototype.constructor=db;g=db.prototype;g.Y=function(){return"IndexedSeq"};g.o=function(){var a=new de(this);return new Rd(a)};g.fa=function(a){var b=this.A.h();return b===a?0:b<a?-1:1};g.h=function(){return this.A.h()};g.x=function(){return this.A.h()};g.i=function(){return this.A.f};g.e=function(){return 0===this.A.h()};g.v=function(a){return new n(65535&(this.A.f.charCodeAt(a)|0))};
g.$classData=L({sd:0},"scala.collection.mutable.StringBuilder",{sd:1,ie:1,Ua:1,Da:1,b:1,Fa:1,y:1,Ha:1,z:1,Ga:1,Ia:1,Sa:1,Na:1,Ja:1,D:1,re:1,pe:1,se:1,le:1,Oa:1,qe:1,je:1,me:1,ke:1,ne:1,vb:1,wb:1,oe:1,hb:1,c:1});m=new v(0,0);ra.Jb=m;var Tc=null;new (N(ld).r)([]);
try{O();var ya;bb||(bb=new ab);ya=document.body;xa();O();O().d.a[0].a[0].value="2";O().d.a[0].a[2].value="4";O().d.a[0].a[4].value="7";O().d.a[0].a[5].value="9";O().d.a[0].a[6].value="5";O().d.a[1].a[4].value="5";O().d.a[1].a[8].value="6";O().d.a[2].a[1].value="6";O().d.a[2].a[4].value="2";O().d.a[2].a[5].value="3";O().d.a[2].a[6].value="1";O().d.a[3].a[2].value="3";O().d.a[3].a[7].value="4";O().d.a[4].a[0].value="6";O().d.a[4].a[2].value="5";O().d.a[4].a[6].value="9";O().d.a[4].a[8].value="1";O().d.a[5].a[1].value=
"2";O().d.a[5].a[6].value="3";O().d.a[6].a[2].value="6";O().d.a[6].a[3].value="5";O().d.a[6].a[4].value="9";O().d.a[6].a[7].value="1";O().d.a[7].a[0].value="1";O().d.a[7].a[4].value="4";O().d.a[8].a[2].value="8";O().d.a[8].a[3].value="3";O().d.a[8].a[4].value="1";O().d.a[8].a[6].value="2";O().d.a[8].a[8].value="7"}catch(a){throw a;};
}).call(this);
//# sourceMappingURL=main.js.map
